name: audio_wave
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.simform.audiowave.audio_wave
        pluginClass: AudioWavePlugin
      ios:
        pluginClass: AudioWavePlugin
